In [1]:
import numpy as np 

In [2]:
vec = np.array([1, 2, 3])
vec.ndim

1

In [3]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

In [4]:
vec.shape

(3,)

In [5]:
mat.dtype.name

'int32'

In [6]:
mat.itemsize

4

In [7]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [8]:
A = np.array([1, 2, 3], dtype = float)
A

array([1., 2., 3.])

In [9]:
B = np.array([(1, 2, 3), (4, 5, 6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.zeros((3,))

array([0., 0., 0.])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty((2, 5))

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [15]:
np.arange(2.5, 8.7, 0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [16]:
np.linspace(2, 18, 14)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [17]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(8).reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
C = np.arange(6).reshape(2, -1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [21]:
A = np.arange(6).reshape(2, -1)
np.hstack((A,A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [22]:
np.vstack((A,A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [23]:
np.concatenate((A, A**2),axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [24]:
a = np.arange(3)
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [25]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [26]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [27]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
A+B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [29]:
A*1.0/B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [30]:
A+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
3*A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [32]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [33]:
A*B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [34]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [35]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [36]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [37]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
A.min()

0

In [39]:
A.max(axis=0)

array([6, 7, 8])

In [40]:
A.sum(axis=1)

array([ 3, 12, 21])

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[2:5]

array([2, 3, 4])

In [43]:
a[3:8:2]

array([3, 5, 7])

In [44]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [45]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [46]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [47]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [48]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [49]:
A = np.arange(81).reshape(9, -1)

In [50]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [51]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

In [52]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [54]:
A[np.logical_and(A != 7, A % 5 != 3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [55]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [56]:
start = time.perf_counter()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.perf_counter() - start)

0.22110709999999978


In [57]:
start = time.perf_counter()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.perf_counter()-start)

0.1820770000000005


In [58]:
start = time.perf_counter()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.perf_counter()-start)

0.006485699999999817


In [59]:
start = time.perf_counter()
ans = A_quick_arr.dot(B_quick_arr)
print(time.perf_counter() - start)

0.01428660000000015
